
import com.exercise.model.AccountAccount;

global java.util.ArrayList violations;

dialect "mvel"

rule "Account must initialized"
	salience 100
	agenda-group "account"
	when
		$first: AccountAccount();
		AccountAccount(this == $first);
	then
		//modify(violations){add("account-already-initialized")};
		violations.add("account-already-initialized");
end





//https://stackoverflow.com/questions/47605657/drools-execute-specific-rules-from-kie-container-based-on-a-parameter